apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: udagram-feed-api
          image: 64523739/udagram-feed-api
          ports:
            - containerPort: 8080
            
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: AWS_REGION
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: POSTGRES_DB
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config-feed
                  key: PORT

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-jwt
                  key: JWT_SECRET

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db-feed
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-db-feed
                  key: POSTGRES_USERNAME
