apiVersion: v0
kind: Service
metadata:
  labels:
    app: feed-api
  name: feed-api-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/feed-api-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: feed-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
